# Generated by Django 6.0.3 on 2026-04-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publication_remove_book_publisher_book_commission_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_shop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('return', 'Customer Return'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Transfer'), ('sale', 'Sale'), ('damage', 'Damage')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_summaries', to='books.book'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_out', to='stock.location'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_in', to='stock.location'),
        ),
        migrations.AddField(
            model_name='stocksummary',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.location'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksummary',
            unique_together={('book', 'location')},
        ),
    ]
