# Generated by Django 6.0.3 on 2026-04-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_publication_remove_book_discount_value_and_more'),
        ('stock', '0002_location_alter_stockentry_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='location_to',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='location_from',
        ),
        migrations.RenameField(
            model_name='stocksummary',
            old_name='quantity',
            new_name='godown_quantity',
        ),
        migrations.AlterUniqueTogether(
            name='stocksummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='location',
            field=models.CharField(choices=[('godown', 'Godown (গুদাম)'), ('shop', 'Shop (দোকান)')], default='godown', max_length=20),
        ),
        migrations.AddField(
            model_name='stocksummary',
            name='shop_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('return', 'Customer Return'), ('adjustment', 'Manual Adjustment')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_summary', to='books.book'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('from_location', models.CharField(choices=[('godown', 'Godown (গুদাম)'), ('shop', 'Shop (দোকান)')], max_length=20)),
                ('to_location', models.CharField(choices=[('godown', 'Godown (গুদাম)'), ('shop', 'Shop (দোকান)')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='stocksummary',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
