# Generated by Django 6.0.3 on 2026-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockentry_location_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='New buy price per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name if source is purchase', max_length=200),
        ),
    ]
