# Generated by Django 6.0.3 on 2026-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockentry_purchase_price_stockentry_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('return', 'Customer Return'), ('adjustment', 'Manual Adjustment'), ('damage', 'Damage/Expired')], default='purchase', max_length=20),
        ),
    ]
