# Generated by Django 6.0.3 on 2026-04-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='কমিশন %', max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage (%)')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_set',
            field=models.BooleanField(default=False, help_text='এটি কি একাধিক বইয়ের সেট/সিরিজ?'),
        ),
        migrations.AddField(
            model_name='book',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='বইয়ের গায়ে লেখা দাম (MRP)', max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publication'),
        ),
    ]
