# Generated by Django 6.0.3 on 2026-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publication_remove_book_publisher_book_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_set',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('single', 'Single Book'), ('series', 'Set (Series)')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'টাকা'), ('percentage', '%')], default='amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='বইয়ের গায়ে থাকা দাম', max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product Code', max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
