# Generated by Django 6.0.7 on 2026-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_publication_remove_book_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('own', 'নিজস্ব প্রকাশনা (তারুণ্য প্রকাশন)'), ('external', 'বাইরের প্রকাশনী/ভেন্ডর')], default='own', help_text='নিজেদের বই নাকি বাইরের প্রকাশনী থেকে কেনা', max_length=20),
        ),
    ]
