# Generated by Django 6.0.7 on 2026-08-02 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_remove_book_publication_remove_book_discount_value_and_more'),
        ('sales', '0014_externaltrade_body_rate_externaltrade_publisher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('vendor_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('opening_due', models.DecimalField(decimal_places=2, default=0, help_text='শুরুর বকেয়া', max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=300)),
                ('memo_number', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_name', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=20)),
                ('location', models.CharField(choices=[('godown', 'Godown (গুদাম)'), ('shop', 'Shop (দোকান)')], default='godown', help_text='বই কোথায় স্টকে যোগ হয়েছে', max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('partial', 'Partial')], default='paid', max_length=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('legacy_external_trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_bill', to='sales.externaltrade')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='প্রতি কপি ক্রয়মূল্য', max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='বিক্রয় কমিশন %', max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasebill')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='books.book')),
            ],
        ),
    ]
