# Generated by Django 5.2.16 on 2026-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_vendorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='এই পেমেন্টের সাথে দেওয়া বাড়তি ছাড় (বিল ক্লোজ করার জন্য)', max_digits=10),
        ),
    ]
