# Generated by Django 6.0.3 on 2026-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_purchase_supplier_sale_previous_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='mrp',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
