# Generated by Django 6.0.3 on 2026-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'খুচরা (Retail)'), ('wholesale', 'পাইকারি (Wholesale)')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default discount %', max_digits=5),
        ),
    ]
