# Generated by Django 6.0.3 on 2026-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_customer_customer_type_customer_default_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20),
        ),
    ]
