# Generated by Django 6.0.3 on 2026-05-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='শুরুর বকেয়া', max_digits=12),
        ),
    ]
