# Generated by Django 6.0.3 on 2026-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='other_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='packaging_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
