# Generated by Django 6.0.3 on 2026-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_delivery_charge_sale_other_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='other_charge',
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
