# Generated by Django 6.0.7 on 2026-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_sale_delivery_charge_remove_sale_other_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='প্রতি কপি ক্রয়মূল্য (নগদ)', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='প্রতি কপি বিক্রয়মূল্য', max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'বিক্রয় বাকি'), ('sold', 'বিক্রি সম্পন্ন')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
