# Generated by Django 6.0.7 on 2026-08-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_publication_remove_book_discount_value_and_more'),
        ('sales', '0012_externaltrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltrade',
            name='converted_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_trade_origins', to='books.book'),
        ),
    ]
