# Generated by Django 6.0.7 on 2026-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_externaltrade_converted_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltrade',
            name='body_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='প্রকাশনীর বডি রেট/কভার প্রাইস', max_digits=10),
        ),
        migrations.AddField(
            model_name='externaltrade',
            name='publisher',
            field=models.CharField(blank=True, help_text='প্রকাশনীর নাম', max_length=300),
        ),
        migrations.AddField(
            model_name='externaltrade',
            name='purchase_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='বডি রেট থেকে কত % কমিশনে কেনা হয়েছে', max_digits=5),
        ),
        migrations.AddField(
            model_name='externaltrade',
            name='sale_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='বডি রেট থেকে কত % কমিশনে বিক্রি হয়েছে/হবে', max_digits=5),
        ),
    ]
