# Generated by Django 5.2.16 on 2026-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_externaltrade_body_rate_externaltrade_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='এই পেমেন্টের সাথে দেওয়া বাড়তি ছাড় (ইনভয়েস ক্লোজ করার জন্য)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('mobile', 'Mobile Banking'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
